### ISSUE TITLE
looping

### ISSUE THREAD

**Issue by jamalnggau1** [zuydd/banana#1]
no looping?

**Comment by zuydd** [comment]
Can loop after claim time

**Comment by jamalnggau1** [comment]
I want after all accounts are finished it will be restarted from the first account.

**Comment by jamalnggau1** [comment]
> I want after all accounts are finished it will be restarted from the first account.

automatically

**Comment by zuydd** [comment]
that doesn't make any sense because doing so just wastes more resources and gets nothing. Restart time is scientifically calculated. If you want you can edit it to your liking, I also have to support many others
