### ISSUE TITLE
Làm sao để đỡ phải lấy query-id

### ISSUE THREAD

**Issue by HoanDao** [zuydd/banana#3]
E làm theo bác lấy query-id từ game khác qua mà ko được bác ạ. Có Tool nào để lấy nhanh hàng loạt ko. tele e dùng loại tdata mở trực tiếp bản portal

**Comment by zuydd** [comment]
data game nào chạy riêng game đó nhé, lấy nhanh chỉ có cách dùng gpm login thôi
