### ISSUE TITLE
 Request failed with status code 429 và 403

### ISSUE THREAD

**Issue by tuanteku9x** [zuydd/banana#4]
========== Đăng nhập tài khoản 1 | Mỹ Duyên 🦴 ==========
[ No 1 _ ID: 5622632763 _ IP: 🖥️ ] Request failed with status code 429
========== Đăng nhập tài khoản 2 | Ngoc Bae 🦴 ==========
[ No 2 _ ID: 7255409818 _ IP: 🖥️ ] Request failed with status code 403

**Comment by painterzeou** [comment]
Same

**Comment by zuydd** [comment]
Fixed, download v0.0.6 and read guide in readme
