### ISSUE TITLE
Lỗi dừng chương trình

### ISSUE THREAD

**Issue by HoanDao** [zuydd/banana#6]
CHương trình e tải về chạy mà nó báo như này là lỗi gì bác. E chạy thư viện rồi ạ

🚀 Cập nhật các tool mới nhất tại: 👉 https://github.com/zuydd 👈

undefined:1
undefined
^

SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at file:///F:/CONG%20VIEC/1.%20XAY%20DUNG/MY%20ID/ADR/1.%20Tool%20auto/Banana/Banana%200.8/src/services/user.js:36:27
    at Array.map (<anonymous>)
    at UserService.loadUser (file:///F:/CONG%20VIEC/1.%20XAY%20DUNG/MY%20ID/ADR/1.%20Tool%20auto/Banana/Banana%200.8/src/services/user.js:34:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///F:/CONG%20VIEC/1.%20XAY%20DUNG/MY%20ID/ADR/1.%20Tool%20auto/Banana/Banana%200.8/src/run/index.js:188:15

Node.js v20.17.0
PS F:\CONG VIEC\1. XAY DUNG\MY ID\ADR\1. Tool auto\Banana\Banana 0.8>

**Comment by zuydd** [comment]
này là do không coi hdsd chứ sao, để data sai chỗ lấy gì nó chạy

**Comment by HoanDao** [comment]
> này là do không coi hdsd chứ sao, để data sai chỗ lấy gì nó chạy

Ủa vậy để chỗ nào mới đúng bác. Em để trong scr/data/users.txt

![image](https://github.com/user-attachments/assets/ac161187-2f8f-45b3-99db-3c1792d1c1ef)

**Comment by zuydd** [comment]
bạn lấy data bằng cách nào, chụp hình data xem, chụp mỗi cái log trong khi vấn đề nằm ở data bị sai định dạng

**Comment by HoanDao** [comment]
> bạn lấy data bằng cách nào, chụp hình data xem, chụp mỗi cái log trong khi vấn đề nằm ở data bị sai định dạng

Data e lấy bằng tay. Lấy trực tiếp trong devtool của tele.  Chụp cái kia là để bác thấy vị trí e đặt file users.txt đúng chưa thôi.

![image](https://github.com/user-attachments/assets/00c9eef5-2239-48ba-87de-6916805543cc)
![image](https://github.com/user-attachments/assets/97036443-50b7-4d20-88f1-6b89ed9cf9a6)

**Comment by zuydd** [comment]
bạn ib tele mình 1 data bị lỗi mình check cho nhé, đừng gửi lên đây bị lộ
